# Generated by Django 3.1.4 on 2020-12-27 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='preference',
            name='action',
            field=models.IntegerField(choices=[(1, 'like'), (2, 'unlike')], null=True),
        ),
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together={('user', 'post', 'action')},
        ),
        migrations.RemoveField(
            model_name='preference',
            name='value',
        ),
    ]
