# Generated by Django 3.1.4 on 2020-12-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201227_1556'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together=set(),
        ),
    ]
